// deno-lint-ignore-file no-explicit-any

const NOTICE =
  `// This file was auto-generated by @rawrxd/revolt-api - do not edit manually\n`;
const OUTPUT_DIR = "out";
const OPENAPI_FILE = "openapi.json";
const BASE_MOD_FILE = "base/mod.ts";
const BASE_URL_FILE = `${OUTPUT_DIR}/baseURL.ts`;
const ROUTES_FILE = `${OUTPUT_DIR}/routes.ts`;
const TYPES_FILE = `${OUTPUT_DIR}/types.ts`;

Deno.mkdirSync(OUTPUT_DIR, { recursive: true });

Deno.copyFileSync(BASE_MOD_FILE, `${OUTPUT_DIR}/mod.ts`);

async function main() {
  try {
    let data = await Deno.readTextFile(OPENAPI_FILE);

    if (Deno.env.get("REWRITE_ANYOF")) {
      data = data.replace(/"anyOf"/g, '"oneOf"');
    }

    const spec = JSON.parse(data);

    generateRoutes(spec);

    await generateTypes(spec);

    writeBaseURL(spec);
  } catch (error) {
    console.error("An error occurred during code generation:", error);
  }
}

await main();

function writeBaseURL(spec: any) {
  const servers = spec.servers;
  let baseURL: string | undefined;

  if (Array.isArray(servers) && servers.length > 0) {
    baseURL = servers[0].url;
  }

  Deno.writeTextFileSync(
    BASE_URL_FILE,
    NOTICE +
      `export const defaultBaseURL = ${
        baseURL ? `"${baseURL}"` : "undefined"
      };`,
  );
}

//
// Route Generator
//

interface OpenAPISpec {
  paths: Record<string, PathItemObject>;
}

interface PathItemObject {
  [method: string]: OperationObject;
}

interface OperationObject {
  parameters?: (ParameterObject | ReferenceObject)[];
  requestBody?: RequestBodyObject | ReferenceObject;
  responses: Record<string, ResponseObject | ReferenceObject>;
}

interface ParameterObject {
  name: string;
  in: string;
  required?: boolean;
  schema?: SchemaObject | ReferenceObject;
}

interface RequestBodyObject {
  content: Record<string, MediaTypeObject>;
  required?: boolean;
}

interface ResponseObject {
  description?: string;
  content?: Record<string, MediaTypeObject>;
}

interface MediaTypeObject {
  schema?: SchemaObject | ReferenceObject;
}

interface ReferenceObject {
  $ref: string;
}

interface SchemaObject {
  type?: string;
  items?: SchemaObject | ReferenceObject;
  properties?: Record<string, SchemaObject | ReferenceObject>;
  required?: string[];
  additionalProperties?: SchemaObject | ReferenceObject | boolean;
  oneOf?: (SchemaObject | ReferenceObject)[];
  anyOf?: (SchemaObject | ReferenceObject)[];
  allOf?: (SchemaObject | ReferenceObject)[];
}

function generateRoutes(spec: OpenAPISpec): void {
  const entries: string[] = [];
  const typeImports = new Set<string>();
  const routeEntries: string[] = ["export type APIRoutes ="];

  const paths = Object.keys(spec.paths);

  for (const path of paths) {
    const pathItemObject = spec.paths[path];
    const methods = Object.keys(pathItemObject);

    const template = path.replace(/\{(\w+)\}/g, () => "${string}");

    for (const method of methods) {
      if (
        !["get", "post", "put", "patch", "delete", "options", "head", "trace"]
          .includes(method)
      ) {
        continue;
      }

      const operationObject = pathItemObject[method] as OperationObject;

      const paramsProperties = processParameters(
        operationObject.parameters || [],
        typeImports,
        spec,
      );

      const requestBodyType = processRequestBody(
        operationObject.requestBody,
        typeImports,
        spec,
      );

      let paramsType = "undefined";
      if (paramsProperties.length > 0 || requestBodyType) {
        const properties = paramsProperties.map((p) => {
          const optional = p.required ? "" : "?";
          return `${p.name}${optional}: ${p.type}`;
        });

        if (requestBodyType) {
          properties.push(`body: ${requestBodyType}`);
        }

        paramsType = `{ ${properties.join("; ")} }`;
      }

      const responseType = processResponses(
        operationObject.responses,
        typeImports,
        spec,
      );

      const pathParamsType = "undefined";

      routeEntries.push(
        `| {
        method: '${method}';
        path: \`${template}\`;
        pathParams: ${pathParamsType};
        params: ${paramsType};
        response: ${responseType};
      }`,
      );
    }
  }

  if (typeImports.size > 0) {
    entries.push(
      `import type { ${[...typeImports].join(", ")} } from './types.ts';`,
    );
  }

  entries.push(...routeEntries);

  Deno.writeTextFileSync(ROUTES_FILE, NOTICE + entries.join("\n") + ";");
}

function processParameters(
  parameters: (ParameterObject | ReferenceObject)[],
  typeImports: Set<string>,
  spec: any,
): { name: string; type: string; required: boolean }[] {
  const paramsProperties: { name: string; type: string; required: boolean }[] =
    [];

  for (const parameter of parameters) {
    let paramObject: ParameterObject;

    if ("$ref" in parameter) {
      paramObject = resolveReference<ParameterObject>(parameter.$ref, spec);
    } else {
      paramObject = parameter;
    }

    if (paramObject.in === "path") {
      continue;
    }

    const paramName = paramObject.name.replace(/-/g, "_");

    const { required = false, schema } = paramObject;

    let paramType = "unknown";
    if (schema) {
      paramType = getTypeFromSchema(schema, typeImports, spec);
    }

    paramsProperties.push({
      name: paramName,
      type: paramType,
      required,
    });
  }

  return paramsProperties;
}

function processRequestBody(
  requestBody: RequestBodyObject | ReferenceObject | undefined,
  typeImports: Set<string>,
  spec: any,
): string | null {
  if (!requestBody) {
    return null;
  }

  let requestBodyObject: RequestBodyObject;

  if ("$ref" in requestBody) {
    requestBodyObject = resolveReference<RequestBodyObject>(
      requestBody.$ref,
      spec,
    );
  } else {
    requestBodyObject = requestBody;
  }

  const requestBodyContent = requestBodyObject.content;
  const contentTypes = Object.keys(requestBodyContent);
  if (contentTypes.length > 0) {
    const contentType = contentTypes[0];
    const mediaTypeObject = requestBodyContent[contentType];
    if (mediaTypeObject.schema) {
      return getTypeFromSchema(mediaTypeObject.schema, typeImports, spec);
    }
  }

  return null;
}

function processResponses(
  responses: Record<string, ResponseObject | ReferenceObject>,
  typeImports: Set<string>,
  spec: any,
): string {
  const responseTypes: Set<string> = new Set();

  for (const code of Object.keys(responses)) {
    let responseObject: ResponseObject;

    if ("$ref" in responses[code]) {
      responseObject = resolveReference<ResponseObject>(
        (responses[code] as ReferenceObject).$ref,
        spec,
      );
    } else {
      responseObject = responses[code] as ResponseObject;
    }

    const responseContent = responseObject.content;
    if (responseContent) {
      const contentTypes = Object.keys(responseContent);
      if (contentTypes.length > 0) {
        const contentType = contentTypes[0];
        const mediaTypeObject = responseContent[contentType];
        if (mediaTypeObject.schema) {
          const type = getTypeFromSchema(
            mediaTypeObject.schema,
            typeImports,
            spec,
          );
          responseTypes.add(type);
        }
      }
    }
  }

  return responseTypes.size > 0 ? [...responseTypes].join(" | ") : "void";
}

function getTypeFromSchema(
  schema: SchemaObject | ReferenceObject,
  typeImports: Set<string>,
  spec: any,
): string {
  if ("$ref" in schema) {
    const typeName = getTypeNameFromRef(schema.$ref);
    typeImports.add(typeName);
    return typeName;
  } else {
    if (
      schema.type === "string" ||
      schema.type === "number" ||
      schema.type === "boolean" ||
      schema.type === "integer"
    ) {
      return schema.type === "integer" ? "number" : schema.type;
    } else if (schema.type === "array" && schema.items) {
      const itemsType = getTypeFromSchema(schema.items, typeImports, spec);
      return `${itemsType}[]`;
    } else if (schema.type === "object") {
      return "Record<string, unknown>";
    } else {
      return "unknown";
    }
  }
}

function getTypeNameFromRef(ref: string): string {
  const parts = ref.split("/");
  const typeName = parts[parts.length - 1];
  if (typeName) {
    return typeName.replace(/-/g, "_");
  } else {
    throw new Error(`Invalid $ref format: ${ref}`);
  }
}

function resolveReference<T>(ref: string, spec: any): T {
  if (!ref.startsWith("#/")) {
    throw new Error(`Unsupported $ref format: ${ref}`);
  }

  const pathParts = ref.slice(2).split("/");

  let current: any = spec;
  for (const part of pathParts) {
    const key = decodeURIComponent(part);
    if (current[key] !== undefined) {
      current = current[key];
    } else {
      throw new Error(`Could not resolve reference: ${ref}`);
    }
  }

  return current as T;
}

//
// Type Generator
//

interface Schema {
  type?: string;
  properties?: { [key: string]: any };
  required?: string[];
  nullable?: boolean;
  additionalProperties?: any;
  items?: any;
  enum?: any[];
  anyOf?: Schema[];
  oneOf?: Schema[];
  allOf?: Schema[];
  $ref?: string;
}

async function generateTypes(spec: any) {
  if (!spec.components || !spec.components.schemas) {
    return;
  }

  const schemas = spec.components.schemas;
  const entries = [];

  for (const [schemaName, schema] of Object.entries<Schema>(schemas)) {
    const typeDefinition = generateTypeDefinition(schemaName, schema, spec);
    entries.push(typeDefinition);
  }

  let output = entries.join("\n") + ";";
  output = output.replace(/export type (\w+)/g, (_match, typeName) => {
    return `export type ${typeName.replace(/\s+/g, "_")}`;
  });
  output = output.replace(/components\["schemas"\]\["([^"]+)"\]/g, "$1");
  output = output.replace(/Authifier Error/g, "Authifier_Error");
  output = output.replace(/ISO8601 Timestamp/g, "ISO8601_Timestamp");

  await Deno.writeTextFile(TYPES_FILE, NOTICE + output);
}

// Helper Functions for Type Generator

function generateTypeDefinition(
  schemaName: string,
  schema: Schema,
  spec: any,
): string {
  if (schema.anyOf || schema.oneOf) {
    if (schema.properties || schema.additionalProperties !== undefined) {
      const rootPropertiesSchema: Schema = {
        type: "object",
        properties: schema.properties,
        required: schema.required,
        additionalProperties: schema.additionalProperties,
        nullable: schema.nullable,
      };

      const baseType = formatSchema(rootPropertiesSchema, spec);

      const variants = (schema.anyOf || schema.oneOf)!.map(
        (subSchema: Schema) => {
          return formatSchema(subSchema, spec);
        },
      );

      const unionType = variants.join(" | ");
      return `export type ${schemaName} = ${baseType} & (${unionType});`;
    } else {
      const types = (schema.anyOf || schema.oneOf)!.map((subSchema: Schema) =>
        formatSchema(subSchema, spec)
      );
      const unionType = types.join(" | ");
      return `export type ${schemaName} = ${unionType};`;
    }
  } else if (schema.allOf) {
    const types = schema.allOf.map((subSchema: Schema) =>
      formatSchema(subSchema, spec)
    );
    const tsType = types.join(" & ");
    return `export type ${schemaName} = ${tsType};`;
  } else if (
    schema.type === "object" ||
    schema.properties ||
    schema.additionalProperties !== undefined
  ) {
    const tsType = formatSchema(schema, spec);
    return `export type ${schemaName} = ${tsType};`;
  } else if (schema.$ref) {
    const refKey = getTypeNameFromRef(schema.$ref);
    return `export type ${schemaName} = ${refKey};`;
  } else {
    const tsType = formatSchema(schema, spec);
    return `export type ${schemaName} = ${tsType};`;
  }
}

function formatSchema(schema: Schema, spec: any): string {
  if (schema.$ref) {
    const refKey = getTypeNameFromRef(schema.$ref);
    return refKey;
  } else if (schema.anyOf || schema.oneOf) {
    const types = (schema.anyOf || schema.oneOf)!.map((subSchema: Schema) =>
      formatSchema(subSchema, spec)
    );
    let tsType = types.join(" | ");
    if (schema.nullable) {
      tsType += " | null";
    }
    return tsType;
  } else if (schema.allOf) {
    const types = schema.allOf.map((subSchema: Schema) =>
      formatSchema(subSchema, spec)
    );
    let tsType = types.join(" & ");
    if (schema.nullable) {
      tsType += " | null";
    }
    return tsType;
  } else if (
    schema.type === "object" ||
    schema.properties ||
    schema.additionalProperties !== undefined
  ) {
    const properties = formatObjectProperties(schema, spec);
    let tsType = `{\n${properties}\n}`;
    if (schema.nullable) {
      tsType += " | null";
    }
    return tsType;
  } else if (schema.type === "array") {
    const itemType = schema.items
      ? formatSchema(schema.items, spec)
      : "unknown";
    let tsType = `${itemType}[]`;
    if (schema.nullable) {
      tsType += " | null";
    }
    return tsType;
  } else if (schema.enum) {
    const enumValues = schema.enum.map((value: any) => JSON.stringify(value))
      .join(" | ");
    let tsType = enumValues;
    if (schema.nullable) {
      tsType += " | null";
    }
    return tsType;
  } else if (schema.type) {
    let tsType = mapPrimitiveType(schema.type);
    if (schema.nullable) {
      tsType += " | null";
    }
    return tsType;
  } else {
    return "unknown";
  }
}

function formatObjectProperties(schema: Schema, spec: any): string {
  const requiredProperties = schema.required || [];
  const properties: string[] = [];

  if (schema.properties) {
    properties.push(
      ...Object.entries(schema.properties).map(([key, prop]) => {
        const isRequired = requiredProperties.includes(key);
        const propName = key.replace(/-/g, "_");
        return formatProperty(propName, prop, isRequired, spec);
      }),
    );
  }

  if (schema.additionalProperties !== undefined) {
    const valueType = formatSchema(schema.additionalProperties, spec);
    properties.push(`  [key: string]: ${valueType};`);
  }

  return properties.join("\n");
}

function formatProperty(
  key: string,
  prop: any,
  isRequired: boolean,
  spec: any,
): string {
  const optionalMark = isRequired ? "" : "?";
  const tsType = formatSchema(prop, spec);
  return `  ${key}${optionalMark}: ${tsType};`;
}

function mapPrimitiveType(type: string): string {
  switch (type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "object":
      return "{ [key: string]: unknown }";
    default:
      return "unknown";
  }
}